version: '3.3'

services:

  nginx:
    build:
      dockerfile: nginx/prod/Dockerfile
    volumes:
      - ./nginx/prod/prod.conf:/etc/nginx/nginx.conf:ro

  frontend:
    build:
      dockerfile: prod/Dockerfile
    environment:
      - PRODUCTION=1
